M7R0
I%Blks7[p7$X,%)anythingG6"F'[gl!"%!!!#1"%"%"""""!F)F)F)F)F(F)F)F)F)F(F)F(F)F)X,
F&F'F'[gl!"%!!!#1"%"%F(F(F(F(&%"xG6#""#F+F(&F,6#F(&F,6#""$*(F/!""F+F(F1F(F(F1F(
F+F(F17$X,F&F'F'[gl!"%!!!#1"%"%F)F)F(F)F(F)F)F)F)F(F)F)F)F)F)F(X,F&F'F'[gl!"%!!
!#1"%"%F(F(F(F(F(F(F1F/F(F1F1*(F/F(F+F5F1F(F(F/F+F/7$X,F&F'F'[gl!"%!!!#1"%"%F)F
)F)F(F)F(F)F)F(F)F)F)F)F)F(F)X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F4F4F(F1F/F+F(F/F(F
4F(F/7$X,F&F'F'[gl!"%!!!#1"%"%F)F(F)F)F)F)F)F(F)F)F(F)F(F)F)F)X,F&F'F'[gl!"%!!!
#1"%"%F(F(F(F(F(F(F/F1F(F/F/F+F(F1F9F17$F;X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F1F1F(
F9F/F+F(F/F(F1F(F/7$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F1F/F(F1F1F9F(F/F+F/7$
F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F+F1F(F+F+F/F(F1F4F17$F>X,F&F'F'[gl!"%!!!#
1"%"%F(F(F(F(F+F+F(*(F/F(F+F(F1F5F+F(F(F/F1F/F(F/7$F;X,F&F'F'[gl!"%!!!#1"%"%F(F
(F(F(F/F/F(F+F1F9F(F1F(F/F(F17$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F/F/F(F1F/F(F(F
+FHF+F(F+7$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F1F1F(F/F1F(F(F+F4F+F(F+7$F;X,F&F'F
'[gl!"%!!!#1"%"%F(F(F(F(F(F(F1*$F+F5F(F+F/F(F(*$F1F5F(*$F/F57$F7X,F&F'F'[gl!"%!
!!#1"%"%F(F(F(F(F(F(F/F4F(F/F/F+F(F4F1F47$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(
F+F9F(F+F+F1F(F9F/F97$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F/F+F(F/F/FHF(F+F1F+
7$F%X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(FRF+F(FQFSF(F(F1F(F/7$F>X,F&F'F'[gl!"%!!
!#1"%"%F(F(F(F(F(F(FHF1F(FHFHF+F(F1F/F17$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F/F/F
(F9F/F(F(F1F+F1F(F17$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(FHFHF(F+FHF(F(F1F/F1F(F17
$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F1F1F(F/F1F(F(F+F4F+F(F+7$F>X,F&F'F'[gl!"%!!!
#1"%"%F(F(F(F(F/F/F(F+F/F(F(F1F9F1F(F17$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F+
F/F(F+F+F1F(F/FHF/7$F;X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(FSF+F(FQF1F(F(F/F(FR7$
F%X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F/F/F(F+F1F9F(F1F(F/F(F17$F%X,F&F'F'[gl!"%!!!#
1"%"%F(F(F(F(F(F(F+FSF(F/F1F(F(FQF(FR7$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F+F
/F(F+F+FHF(F/F1F/7$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F1F1F(F4F1F(F(F+F/F+F(F+7$F
7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F+F1F(F+F+F4F(F1F/F17$F7X,F&F'F'[gl!"%!!!#1
"%"%F(F(F(F(F(F(F+F/F(F+F+FHF(F/F1F/7$F%X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(FRF+
F(FQFSF(F(F1F(F/7$F;X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F1F1F(F4F+F/F(F+F(F1F(F+7$F>
X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F1F1F(F9F1F(F(F/F+F/F(F/7$F>X,F&F'F'[gl!"%!!!#1"
%"%F(F(F(F(F/F/F(FHF/F(F(F+F1F+F(F+7$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F1F/F
(F1F1F+F(F/F9F/7$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F+F1F(F+F+F4F(F1F/F17$F;X
,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F+FRF(F1F/F(F(FQF(FS7$F%X,F&F'F'[gl!"%!!!#1"%
"%F(F(F(F(F(F(F+F/F(FSF1F(F(FQF(FR7$F;X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F/F+F(
FQF1F(F(FSF(FR7$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F+F+F(F1F+F(F(F/FHF/F(F/7$F%X,
F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(FSF1F(FRFQF(F(F/F(F+7$F;X,F&F'F'[gl!"%!!!#1"%"
%F(F(F(F(F1F1F(F/F+F4F(F+F(F1F(F+7$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F/F/F(F1F/F
(F(F+FHF+F(F+7$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F/F1F(F/F/F+F(F1F9F17$F%X,F
&F'F'[gl!"%!!!#1"%"%F(F(F(F(F1F1F(F9F/F+F(F/F(F1F(F/7$F%X,F&F'F'[gl!"%!!!#1"%"%
F(F(F(F(F+F+F(F4F1F/F(F1F(F+F(F17$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F/F+F(F/
F/F1F(F+FHF+7$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F1F1F(F+F1F(F(F/F9F/F(F/7$F7X,F&
F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(FHF1F(FHFHF+F(F1F/F17$F>X,F&F'F'[gl!"%!!!#1"%"%F
(F(F(F(F(F(F9F+F(F9F9F/F(F+F1F+7$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F1F/F(F1F
1F9F(F/F+F/7$F%X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F+FRF(F1F/F(F(FQF(FS7$F7X,F&F
'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F/F4F(F/F/F1F(F4F+F47$F%X,F&F'F'[gl!"%!!!#1"%"%F(
F(F(F(F1F1F(F4F+F/F(F+F(F1F(F+7$F%X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F+F+F(FHF/F1F(
F/F(F+F(F/7$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F/F4F(F/F/F1F(F4F+F47$F7X,F&F'
F'[gl!"%!!!#1"%"%F(F(F(F(F(F(FHF1F(FHFHF/F(F1F+F17$F;X,F&F'F'[gl!"%!!!#1"%"%F(F
(F(F(F/F/F(F9F1F+F(F1F(F/F(F17$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F1F1F(F9F1F(F(F
/F+F/F(F/7$F%X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(FHFHF(F/F1F+F(F1F(FHF(F17$F;X,F&F'F
'[gl!"%!!!#1"%"%F(F(F(F(F(F(F+FRF(F1FSF(F(FQF(F/7$F%X,F&F'F'[gl!"%!!!#1"%"%F(F(
F(F(F/F/F(FHF+F1F(F+F(F/F(F+7$F;X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F+F+F(F4F1F/F(F1
F(F+F(F17$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F1F+F(F1F1F/F(F+F4F+7$F>X,F&F'F'
[gl!"%!!!#1"%"%F(F(F(F(F1F1F(F+F1F(F(F/F9F/F(F/7$F%X,F&F'F'[gl!"%!!!#1"%"%F(F(F
(F(F(F(F/F1F(FRFQF(F(FSF(F+7$F;X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(FHFHF(F+F1F/F(F1F
(FHF(F17$F;X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F1F1F(F4F+F/F(F+F(F1F(F+7$F%X,F&F'F'[
gl!"%!!!#1"%"%F(F(F(F(F+F+F(F1F/FHF(F/F(F+F(F/7$F%X,F&F'F'[gl!"%!!!#1"%"%F(F(F(
F(F(F(F/F1F(FRFQF(F(FSF(F+7$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F+F+F(F1F+F(F(F/FH
F/F(F/7$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F+F+F(F/F+F(F(F1F4F1F(F17$F7X,F&F'F'[g
l!"%!!!#1"%"%F(F(F(F(F/F/F(F9F/F(F(F1F+F1F(F17$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F
(F/F/F(FHF/F(F(F+F1F+F(F+7$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F1F1F(F+F1F(F(F/F9F
/F(F/7$F7X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(F/F+F(F/F/F1F(F+FHF+7$F7X,F&F'F'[gl
!"%!!!#1"%"%F(F(F(F(F(F(F1F/F(F1F1F+F(F/F9F/7$F>X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(
F+F+F(F1F+F(F(F/FHF/F(F/7$F%X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F/F/F(FHF+F1F(F+F(F/
F(F+7$F;X,F&F'F'[gl!"%!!!#1"%"%F(F(F(F(F(F(FRF+F(FQFSF(F(F1F(F/F'
